name: Repack Mobile

on:
  schedule:
    - cron: '20 3 * * 2'
  workflow_dispatch:
    inputs:
      version:
        description: 'StandardNotes/mobile''s version'
        required: true
        type: string

jobs:
    android:
        defaults:
            run: 
                working-directory: /tmp
        runs-on: ubuntu-latest
        steps: 
            - name: Set version on schedule
              id: cron
              if: github.event.schedule 
              #if: "${{ inputs.version == '' }}"
              run: echo version=$(curl 'https://api.github.com/repos/standardnotes/app/git/matching-refs/tags/@standardnotes/mobile@' |jq -r 'last | .ref | split("@") |last')  >> $GITHUB_OUTPUT
            - name: Download
            #  curl -L -O https://github.com/standardnotes/app/releases/download/@standardnotes/mobile@${{ inputs.version || steps.cron.outputs.version }}/app-prod-release.apk
              run: mkdir -p /tmp/build && curl -L -o /tmp/build/base.zip $(curl https://api.github.com/repos/standardnotes/app/releases/tags/@standardnotes/mobile@${{ inputs.version || steps.cron.outputs.version }} | jq -r '.assets | .[] | select (.name | contains(".apk")) |.browser_download_url' )
                
            - name: Unzip and Patch
              run: cd /tmp/build && unzip base.zip && rm base.zip && sed -i '/isThirdPartyHostUsed(){/isThirdPartyHostUsed(){return false;/' assets/Web.bundle/src/web-src/app.js && zip -r StandardNotes-${{ inputs.version || steps.cron.outputs.version }}.apk * 
            - name: Resign 
              id: resign
              uses: kevin-david/zipalign-sign-android-release@v1.1
              with:
                # Found here https://ask.dcloud.net.cn/article/36522
                # https://download.dcloud.net.cn/keystore/Test.keystore
                releaseDirectory: /tmp/build
                signingKeyBase64: "MIIKDQIBAzCCCcYGCSqGSIb3DQEHAaCCCbcEggmzMIIJrzCCBWsGCSqGSIb3DQEHAaCCBVwEggVYMIIFVDCCBVAGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBQ9edF6BoIxq4TJ9kl9pHhi6+B8kQIDAMNQBIIEyNNYppIVXJ3Mksl09XIBW4EY6ArIolxW51diPQv9ICBqnXZJlaij/q+Osk2skpcCkN2khAj6ImX1dqwSLJJ7cFxALkfeatVU/6+I0jiYqU9vcquUYvjpTQjq7dJ2hqgL3jUQBv0bwwmR2RuRZlUjlPTKhwz+VnOSHlk0rF2xHKgHo8KY5Pstf3WCWWSYJ8QxPC8R0tQWz2+hl8q8fLMRF7FuAUV50ydG35Re/z4a1dd1QqdRw5g1UFCRHm/434KZ2ixB68bcbT1s7OjBy1bAHguCosQ8iNEdodwCYzD0Wc6gY2EI2J7Houu8wgpTJQaXET775IBtrHSU2hHvZ3HU1ziyy2MEYGce73KqJ7CTP4NaLOHUStb+9jTH/f3YtOjdAMA1wgUjF73sQ8e39GUyNHjTSSpCFBwiErYXlBiIdovQsp73xSIB9ZDkK7DvS5NMi0eGpHPkVeFLK5QMJM4bJ0i873m3rnIdJbPT4m0OkaNOb+t/e1oMaya9EMmzrz8q3E1JUWfNogVICGseJIjdSko0bJAsamf/LoUnkYNILaLwoxScxqK+2EiSyXNIb4z5VHwzJXZ+7AVyfZQj5SG8U/r8+dPEuFYEuNrZ+e5z/qUccd62xbVxNNCbllXLWYzfliWIIc7gW6Y3eegr8H0VIgaA6pJToNYX0gp6I4f0pBU0+SVuWpxVNJ93yJ51kNXI7fjPheyNWOawUxckiyHazPgkr+zd7xS4zrFmNESRl+aTJbgR2PZa1hg+DtZxGCsVv356vS1Kzb4H+4DU4HVg7lianDdJvASvpAoM1f45fTluF+5jac5/CGWIQ17ds+8ksErMrnaBvJ/SAa0Pcm70a6dWewk1V0atuz2fd/3tr6ENeV9x5l5ASYY2C+zOgnsSDfKAhrPhPChrynrD/nTPxxbs3UGvHu5IetwaEjq5V3ZiBglPmXtlXZfTZ9FyMwuML5n7oTthg/4RJB4W/wH+G8q+KNHXysV6qN+a8AOR9fsFC3lquYdf6WACTbjN3YA4zyegk3BVJqpuNS8u4t9ELOehZ+NPw4Vkj8Gcp827OD387uoD6J8phbOZB4TdbzC2ND/S0+vPJ8kR1JUdVaVieHVPDJ5sokWXFZIFKTh+P42sEq4IfpIFPoeGVh/cLauV6QlqyAiTsjATRn8t714USc2qG3u+ZL4ZQZMMv61wTXrxoX8k4A90O7952/hc0hn3f+PwAKzBewK7Finy4s7zHR9+cRbCRiOH45U0PMlRSBaMhgodUFGj9dy+CH5wAdkFtv2gzRvfhdzmp39YYNAzIxy5AwobzpPoI3Xltt6Xr/Ch2X0EbX5k5aHU1P+iBAqSpDB1aDFWlyohPUMIGiOxaSS9rBgA3y2JdrkHGxfVCkKqyplVUTcoYQIx3eA/PJ0AOc7LXYq6g58ia8T5R47nXArDeRbINIOPnM1kPFwLGlMyptT+OofAp2aw6lGRp/DjJ580KP8bYiySqvuJWlT+LMH19X6G7QluE1xNCIpVAnbC6AlVLoYTwfKcQeurvFYf98my+GgQu4I0EsxcYVZL2aw2IEEpHUbqLWFtajoKLW6W32eDm2k6XMY0aFB0otssP/yDtRPguAur1eerSFltALMbyqyH57A1ozFCMB0GCSqGSIb3DQEJFDEQHg4AYQBuAGQAcgBvAGkAZDAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNjE4MjE2MDg5MTAwMIIEPAYJKoZIhvcNAQcGoIIELTCCBCkCAQAwggQiBgkqhkiG9w0BBwEwKQYKKoZIhvcNAQwBBjAbBBTlXxebezU+U/lV4t6hpgFr7KiPDwIDAMNQgIID6JH0arkmdmiI86IAkCMTiR+Hx4YWqvXLgH/HpB57EoAAeyjzVBXUD2InZrmX2oyf43F6Y4cPOtnIDfxjBMx7PMCLwJ27DJ6gGduf08NbVeFNlfjdT9LcDOshltZJoS18UzYXiLmVPmZ+10Lnby1e9UG5YkyUvxBZq2lZUimqcsI0Wvv+2x3nOKlpRdWHeZZcuq/5UVoxa5kaUhaGnxfImxdQ3oDkJ9ahl6nHisC5O4CMaGmjHzH0+LRpxb9jjJDC3gVsDGer4YVJLi/sxM/obOFGIeymoqcU1Rtczkro+tt5PBIbDlfovXk7+JNC8MEF4+6DiMo5BVoPnOrNDRHGLSstd2joAbefpMbRQwQtUlQ7B/KB0sjKL4+oX4oAWW0dQHp2F8SXwLLf/yl5bcq7pZ0Wru/Sgibv5d7QgKxyJi6KHiQdjFQMWDl3S47rwOMKLuTj4TCIdfr0xslj39OE0Wqcwr3WVm8d8YndRA9xGFtZqItnIKpy9JzZ63OS9e8CXRFEagwoUXBATLqXXbx9HiVE5Xrog0X3bIkuXY+kRAUOt2uqpialaF7RD0PaYUZUPRgjgYeonBoraagevWNJYFcELMKuHk/LnklFeFrOVm8NV1o/Pg8eyPjN2I2m09rbdt91KXwSUcn0fJM+03MPRHOf1vQawmWGccsOZ8Hz5l3qJAxfHj7T+Afvkli5dd7vYRRttmKyBCi6wIm5eHKklMrmFHOnIL1ORAulCgXL5mCue6N5A9IK4NnZsWORqjsf93UQtIHymzzMCNRTP4OINvKpwA3RYSSLZzThtFxDpb8PQu2eL+q4AcWintYyQn7AQdyp04FbQDRSMBuObcBKSllKUqpXeSSnU0oCIEVsFbKVN7BscuCUM1Roq0noR6Z5+Z621IHdrZeXk4mbBEoAilux4ZhuEiA3o5nTPgjOODQR0+USxCJONzlYqVBwBcAow/KTtMXc6Lnre7GtRHZTvXLhEc/OB6YCUZW3kzjYs6IoV0I0LQc+MttX1sxNZX3vkKa+aOHLOJ5yUyEjewer3TrMfkWr3uv/j/4TCnGoHk6k5U1jCzik3cwLW3KPobt3mKetz+KCxy9M839rgVg6o65BBWM+coZgk1vi4EK5Kb7G8lKDaONTcxoNLNV/Ito8b09F1DKVoQT1gYDUVaHWREpiX8duG0tkqa4NqBkOf9SOzrhdOWlQBtRvRVvmdolu3xNz2C1aq/eu49/yXdRsMmQknzyOVcrHGprxPm82Im9GKEiq04KYj65U+1PmXoK0WMzdR2NbrD/EzsNYH6u7tC02p2D8Gt5zpKJo5uKNcRrjB4S5EzKBkLswPjAhMAkGBSsOAwIaBQAEFK4S0oLDG1pxVDnfrlKnGtc2kyupBBT13hgh9ta24ngfhAKUFO2LJO62PAIDAYag"
                alias: "android"
                keyStorePassword: "123456"
                zipAlign: true
            - name: Upload
              uses: softprops/action-gh-release@v1
              with:
                tag_name: "@standardnotes/mobile@${{ inputs.version || steps.cron.outputs.version }}"
                name: "Mobile ${{ inputs.version || steps.cron.outputs.version }}"
                body: "Custom & Self-signed StandardNotes Mobile ${{ inputs.version || steps.cron.outputs.version }}"
                draft: false
                files: ${{steps.resign.outputs.signedReleaseFile}}

